version: 2.1

parameters:
  run-build-frontend:
    type: boolean
    default: false
  run-build-backend:
    type: boolean
    default: false
  run-build-open-api:
    type: boolean
    default: false
  run-build-root:
    type: boolean
    default: false

jobs:
  build:
    docker: 
      - image: cimg/node:18.9.0
    steps:
      - run:
          command: echo "build!"
  deploy:
    docker:
      - image: cimg/node:18.9.0
    steps:
      - run:
          command: echo "deploy!"


workflows:
  backend:
    when: << pipeline.parameters.run-build-backend >>
    jobs:
      - deploy
  frontend:
    when: << pipeline.parameters.run-build-frontend >>
    jobs:
      - build:
          requires:
            - backend
  open-api:
    when: << pipeline.parameters.run-build-open-api >>
    jobs:
      - build
  app-root:
    when: << pipeline.parameters.run-build-root >>
    jobs:
      - build
  run-integration-tests:
    when:
      or: [<< pipeline.parameters.run-build-frontend >>, << pipeline.parameters.run-build-backend >>]
    jobs:
      - build