version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:18.9.0
parameters:
  run-build-frontend:
    type: boolean
    default: false
  run-build-backend:
    type: boolean
    default: false
  run-build-open-api:
    type: boolean
    default: false
  run-build-root:
    type: boolean
    default: false

jobs:
  migration: 
    executor: default
    steps:
      - run:
          command: echo "migrate"
  build:
    executor: default
    steps:
      - run:
          command: echo "build!"
  deploy:
    executor: default
    steps:
      - run:
          command: echo "deploy!"
  update-traffic:
    executor: default
    steps:
      - run:
          command: echo "update traffice to latest container"

workflows:
  server-layers:
    jobs:
      - migrate
      - build:
          requires: 
            - migrate
      - deploy:
          requires:
            - build
  backend:
    when: << pipeline.parameters.run-build-backend >>
    jobs:
      - build
      - deploy:
          requires: 
            - build
  frontend:
    when: << pipeline.parameters.run-build-frontend >>
    jobs:
      - build
      - deploy:
          requires: 
            - build
  open-api:
    when: << pipeline.parameters.run-build-open-api >>
    jobs:
      - build
      - deploy:
          requires: 
            - build
  app-root:
    when: << pipeline.parameters.run-build-root >>
    jobs:
      - build
      - deploy:
          requires: 
            - build
  update-traffic:
    jobs: 
      - update-traffic:
          requires:
            - server-layers
            - frontend
            - backend
            - open-api