version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:18.9.0
parameters:
  run-build-frontend:
    type: boolean
    default: false
  run-build-backend:
    type: boolean
    default: false
  run-build-open-api:
    type: boolean
    default: false
  run-build-server-layers:
    type: boolean
    default: false
  run-build-root:
    type: boolean
    default: false

jobs:
  migration: 
    executor: default
    steps:
      - run:
          command: echo "migrate"
  build:
    executor: default
    steps:
      - run:
          command: echo "build!"
  deploy:
    executor: default
    steps:
      - run:
          command: echo "deploy!"
  update-traffic:
    executor: default
    steps:
      - run:
          command: echo "update traffice to latest container"

# TODO: 
#    - 条件分岐が複雑になるのでシンプルにしたい
#    - マイグレーションだけなら単独で実行する
#    - マイグレーションと別サービスならこれまでどおり全て実行する
#    - frontend, backendどちらもあるならb→fの順番で実行する
#    - それ以外はサービス単独で実行する
workflows:
  all:
    when:
      and: 
        - << pipeline.parameters.run-build-server-layers >>
        - or:
            - << pipeline.parameters.run-build-frontend >>
            - << pipeline.parameters.run-build-backend >>
            - << pipeline.parameters.run-build-open-api >>
    jobs:
      - migration
      - build:
          requires: 
            - migration
      - deploy:
          requires:
            - build
  only-migration:
    when: 
      and:
        - << pipeline.parameters.run-build-server-layers >>
        - and:
            - not: << pipeline.parameters.run-build-frontend >>
            - not: << pipeline.parameters.run-build-backend >>
            - not: << pipeline.parameters.run-build-open-api >>
    jobs:
      - migration
  front-and-backend:
    when: 
      and: 
        - not: << pipeline.parameters.run-build-server-layers >>
        - << pipeline.parameters.run-build-frontend >>
        - << pipeline.parameters.run-build-backend >>
    jobs:
      - build
      - deploy:
          requires: 
            - build
  backend:
    when: 
      and: 
        - << pipeline.parameters.run-build-backend >>
        - not: << pipeline.parameters.run-build-frontend >>
    jobs:
      - build
      - deploy:
          requires: 
            - build
  frontend:
    when:
      and: 
        - << pipeline.parameters.run-build-frontend >>
        - not: << pipeline.parameters.run-build-backend >>
    jobs:
      - build
      - deploy:
          requires: 
            - build
  open-api:
    when: << pipeline.parameters.run-build-open-api >>
    jobs:
      - build
      - deploy:
          requires: 
            - build
  app-root:
    when: << pipeline.parameters.run-build-root >>
    jobs:
      - build
      - deploy:
          requires: 
            - build
#  update-traffic:
#    jobs: 
#      - update-traffic:
#          requires:
#            - server-layers
#            - frontend
#            - backend
#            - open-api