version: 2.1

parameters:
  run-build-frontend:
    type: boolean
    default: false
  run-build-backend:
    type: boolean
    default: false
  run-build-open-api:
    type: boolean
    default: false
  run-build-root:
    type: boolean
    default: false

jobs:
  hello:
    docker: 
      - image: cimg/node:18.9.0
    steps:
      - run:
          command: echo "hello"

workflows:
  frontend:
    when: << pipeline.parameters.run-build-frontend >>
    jobs:
      - hello:
          requires:
            - backend
  backend:
    when: << pipeline.parameters.run-build-backend >>
    jobs:
      - hello
  open-api:
    when: << pipeline.parameters.run-build-open-api >>
    jobs:
      - hello
  app-root:
    when: << pipeline.parameters.run-build-root >>
    jobs:
      - hello
  run-integration-tests:
    when:
      or: [<< pipeline.parameters.run-build-frontend >>, << pipeline.parameters.run-build-backend >>]
    jobs:
      - hello